spring:
  application:
    name: limits-service
  config:
    import: optional:configserver:http://localhost:8888/
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASS:guest}
  cloud:
    bus:
      enabled: true
      refresh:
        enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
